### ISSUE TITLE
Resources about images

### ISSUE THREAD

**Issue by 1000ch** [danielguillan/perf.rocks#79]
How about following some articles and a tool?

- [We should optimize images](https://medium.com/@1000ch/we-should-optimize-images-8435760e0ec9) - An article which I wrote up on Medium.
- [Introduction to WebP](https://medium.com/@1000ch/introduction-to-webp-b593dfe1d1d1) - An article which I wrote up on Medium.

```yaml
-
    title: 'We should optimize images'
    author: ['Shogo Sensui']
    category: 'image'
    url: https://medium.com/@1000ch/we-should-optimize-images-8435760e0ec9
    tags: ['image']
-
    title: 'Introduction to WebP'
    author: ['Shogo Sensui']
    category: 'image'
    url: https://medium.com/@1000ch/introduction-to-webp-b593dfe1d1d1
    tags: ['image']
```

- [WebPonize](https://webponize.github.io) - a Mac App which converts images into WebP format.

```yaml
-
    name: WebPonize
    description: WebPonize is a Mac OS App for converting PNG, JPEG, animated (or not) GIF images into WebP.
    website: https://webponize.github.io
    category: 'Image Optimization'
    tags: ['image', 'WebP', 'optimization']
```
